# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Sergio Mazzola <smazzola@iis.ee.ethz.ch>

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  # Enable colors in CI terminal
  TERM: ansi
  FORCE_COLOR: 1
  # Configure environment
  # TODO
  # Override pip cache directory
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# -------------------
# Define pipeline stages
# -------------------
# stages:
#   - setup
#   - build
#   - test

default:
  before_script:
    - source iis-env.sh
  cache: &global_cache
    key:
      files:
        - requirements.txt
    paths:
      - .cache/pip
    policy: pull

#########
# Setup #
#########

# setup:
#   # stage: setup
#   cache:
#     # inherit all global cache settings
#     <<: *global_cache
#     # override the policy
#     policy: pull-push
#   script:
#     - echo "Setup completed."

############
# Build all #
############

build-all:
  # stage: build
  # needs: [setup]
  script:
    - bender checkout
    - make chim-all || echo "retrying..."
    - make chim-all

hello-world:
  # stage: test
  needs: [build-all]
  script:
    - echo "Hello world from seyrita-top CI!"